# Install script for directory: G:/zephyr_v4_1_0/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/Zephyr-Kernel")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "C:/Users/cjwsa/zephyr-sdk-0.17.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-objdump.exe")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/arch/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/lib/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/soc/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/boards/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/subsys/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/drivers/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/acpica/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/cmsis/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/cmsis-dsp/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/cmsis-nn/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/fatfs/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/adi/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/altera/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_ambiq/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/atmel/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_espressif/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_ethos_u/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_gigadevice/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_infineon/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_intel/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/microchip/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_nordic/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/nuvoton/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_nxp/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/openisa/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/quicklogic/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_renesas/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_rpi_pico/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_silabs/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_st/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_stm32/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_tdk/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_telink/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/ti/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_wch/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hal_wurthelektronik/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/xtensa/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/hostap/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/liblc3/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/libmctp/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/libmetal/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/littlefs/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/loramac-node/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/lvgl/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/mbedtls/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/mcuboot/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/mipi-sys-t/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/nrf_wifi/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/open-amp/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/openthread/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/percepio/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/picolibc/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/segger/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/tinycrypt/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/trusted-firmware-a/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/trusted-firmware-m/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/uoscore-uedhoc/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/zcbor/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/modules/nrf_hw_models/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/kernel/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/cmake/flash/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/cmake/usage/cmake_install.cmake")
  include("C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/cmake/reports/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "C:/Users/cjwsa/Documents/Zephyr_Projects/mcxw71_sniffer/Sniffer/debug/mcuboot/zephyr/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
